Make httpd management script self-contained for OS X.
From: Lassi Tuura <lat@cern.ch>


git-svn-id: svn+ssh://svn.cern.ch/reps/CMSDMWM/HTTPGroup/trunk@14252 4525493e-7705-40b1-a816-d608a930855b

diff --git a/mkserver b/mkserver
--- a/mkserver
+++ b/mkserver
@@ -297,9 +297,6 @@ TraceEnable		Off
 # config: @SERVER_ROOT@/server.conf
 # pidfile: @SERVER_ROOT@/var/httpd.pid
 
-# Source function library.
-. /etc/rc.d/init.d/functions
-
 # Source run time environment.
 for file in @SERVER_ROOT@/etc/env.d/*.sh; do
   [ -f $file ] || continue
@@ -335,100 +332,145 @@ logfile=@LOGDIR@/start_stop.log
 RETVAL=0
 savedpid=""
 
+success() { echo -ne "[  OK  ]\r"; }
+failure() { echo -ne "[FAILED]\r"; }
+warning() { echo -ne "[WARNING]\r"; }
+
 # A safer approach to get the pid of httpd.  It only seaches for pids
 # based on the full path of an executable file, and returns the parent
 # process. Argument: the full path of the httpd binary
 getpidfromexec() {
-	if [ "$#" -eq 0 ]; then
-	    echo $"Usage: getpidfromexec {program}"
-	    savedpid=''
-	    return 1
-	fi
-        local awkprog="/${1//\//\\/}/ && !/awk/ {printf (\"%d\\n\",\$2)}"
-        savedpid=`ps hauxww --sort ppid | awk "$awkprog" | head -n1`
-	return 0
+  if [ "$#" -eq 0 ]; then
+    echo "Usage: getpidfromexec {program}"
+    savedpid=''
+    return 1
+  fi
+  local sort="--sort ppid"; [ $(uname) = Darwin ] && sort=
+  local awkprog="/${1//\//\\/}/ && !/awk/ {printf (\"%d\\n\",\$2)}"
+  savedpid=`ps hauxww $sort | awk "$awkprog" | head -n1`
+  return 0
+}
+
+# Check if any of $pid (could be plural) are running
+checkpid() {
+  local i
+  for i in $* ; do
+    [ $(ps -o pid= -p $i | wc -l) != 0 ] && return 0
+  done
+  return 1
 }
 
 # Rewriten killproc() from /etc/rc.d/init.d/functions because it was
 # killing other httpd processes when the server had already been stopped
 killproc() {
-        RC=0; delay=3
-        # Test syntax.
-        if [ "$#" -eq 0 ]; then
-                echo $"Usage: killproc [ -d delay] {program} [signal]"
-                return 1
-        fi
-        if [ "$1" = "-d" ]; then
-                delay=$2
-                shift 2
-        fi
+  RC=0; delay=3
+  # Test syntax.
+  if [ "$#" -eq 0 ]; then
+    echo "Usage: killproc [ -d delay] {program} [signal]"
+    return 1
+  fi
+  if [ "$1" = "-d" ]; then
+    delay=$2
+    shift 2
+  fi
 
-        notset=0
-        # check for second arg to be kill level
-        if [ -n "$2" ]; then
-                killlevel=$2
-        else
-                notset=1
-                killlevel="-9"
-        fi
+  notset=0
+  # check for second arg to be kill level
+  if [ -n "$2" ]; then
+    killlevel=$2
+  else
+    notset=1
+    killlevel="-9"
+  fi
 
-        # Save basename.
-        base=${1##*/}
+  # Save basename.
+  base=${1##*/}
 
-        # Find pid.
-        pid=
-        if [ -f $pidfile ]; then
-                local line p
-                read line < $pidfile
-                for p in $line ; do
-                        [ -z "${p//[0-9]/}" -a -d "/proc/$p" ] && pid="$pid $p"
-                done
-        fi
-        # remove the space at the beginning of pid
-        pid=${pid#" "}
-        if [ -z "$pid" ]; then
-                getpidfromexec $1
-                pid=$savedpid
-        fi
+  # Find pid.
+  pid=
+  if [ -f $pidfile ]; then
+    local line p
+    read line < $pidfile
+    for p in $line ; do
+      [ -z "${p//[0-9]/}" -a $(ps -o pid= -p $p | wc -l) != 0 ] && pid="$pid $p"
+    done
+  fi
 
-        # Kill it.
-        if [ -n "${pid:-}" ] ; then
-                [ "$BOOTUP" = "verbose" -a -z "$LSB" ] && echo -n "$base "
-                if [ "$notset" -eq "1" ] ; then
-                       if checkpid $pid 2>&1; then
-                           # TERM first, then KILL if not dead
-                           kill -TERM $pid >/dev/null 2>&1
-                           usleep 100000
-                           if checkpid $pid && sleep 1 &&
-                              checkpid $pid && sleep $delay &&
-                              checkpid $pid ; then
-                                kill -KILL $pid >/dev/null 2>&1
-                                usleep 100000
-                           fi
-                        fi
-                        checkpid $pid
-                        RC=$?
-                        [ "$RC" -eq 0 ] && failure $"$base shutdown" || success $"$base shutdown"
-                        RC=$((! $RC))
-                # use specified level only
-                else
-                        if checkpid $pid; then
-                                kill $killlevel $pid >/dev/null 2>&1
-                                RC=$?
-                                [ "$RC" -eq 0 ] && success $"$base $killlevel" || failure $"$base $killlevel"
-                        fi
-                fi
-        else
-            failure $"$base shutdown"
-            RC=1
-        fi
+  # remove the space at the beginning of pid
+  pid=${pid#" "}
+  if [ -z "$pid" ]; then
+    getpidfromexec $1
+    pid=$savedpid
+  fi
 
-        # Remove pid file if any.
-        if [ "$notset" = "1" ]; then
-            rm -f $pidfile
+  # Kill it.
+  if [ -n "${pid:-}" ] ; then
+    [ "$BOOTUP" = "verbose" -a -z "$LSB" ] && echo -n "$base "
+    if [ "$notset" -eq "1" ] ; then
+      if checkpid $pid 2>&1; then
+        # TERM first, then KILL if not dead
+        kill -TERM $pid >/dev/null 2>&1
+        sleep 0.1
+        if checkpid $pid && sleep 1 &&
+           checkpid $pid && sleep $delay &&
+           checkpid $pid ; then
+          kill -KILL $pid >/dev/null 2>&1
+          sleep 0.1
         fi
-	savedpid=$pid
-        return $RC
+      fi
+      checkpid $pid
+      RC=$?
+      [ "$RC" -eq 0 ] && failure "$base shutdown" || success "$base shutdown"
+      RC=$((! $RC))
+      # use specified level only
+    else
+      if checkpid $pid; then
+        kill $killlevel $pid >/dev/null 2>&1
+        RC=$?
+        [ "$RC" -eq 0 ] && success "$base $killlevel" || failure "$base $killlevel"
+      fi
+    fi
+  else
+    failure "$base shutdown"
+    RC=1
+  fi
+
+  # Remove pid file if any.
+  if [ "$notset" = "1" ]; then
+    rm -f $pidfile
+  fi
+  savedpid=$pid
+  return $RC
+}
+
+daemon() {
+  # Save basename.
+  local base=${1##*/}
+
+  # See if it's already running. Look *only* at the pid file.
+  local pid=
+  if [ -f "$pidfile" ] ; then
+    local line p
+    read line < "$pidfile"
+    for p in $line ; do
+      [ -z "${p//[0-9]/}" -a -d "/proc/$p" ] && pid="$pid $p"
+    done
+  fi
+  [ -n "$pid" ] && return
+
+  # make sure it doesn't core dump anywhere unless requested
+  local corelimit="ulimit -S -c ${DAEMON_COREFILE_LIMIT:-0}"
+
+  # if they set NICELEVEL in /etc/sysconfig/foo, honor it
+  local nice
+  [ -n "${NICELEVEL:-}" ] && nice="nice -n $NICELEVEL"
+
+  # Echo daemon
+  [ "${BOOTUP:-}" = "verbose" -a -z "${LSB:-}" ] && echo -n " $base"
+
+  # And start it up.
+  $nice /bin/bash -c "$corelimit >/dev/null 2>&1 ; $*"
+  [ "$?" -eq 0 ] && success "$base startup" || failure "$base startup"
 }
 
 # The semantics of these two functions differ from the way apachectl does
@@ -436,7 +478,7 @@ killproc() {
 # when not running is also a failure.  So we just do it the way init scripts
 # are expected to behave here.
 start() {
-  echo -n $"Starting $prog: "
+  echo -n "Starting $prog: "
   LANG=C daemon $httpd $OPTIONS
   RETVAL=$?
   echo
@@ -448,8 +490,9 @@ start() {
   fi
   return $RETVAL
 }
+
 stop() {
-  echo -n $"Stopping $prog: "
+  echo -n "Stopping $prog: "
   killproc $httpd
   RETVAL=$?
   echo
@@ -458,12 +501,13 @@ stop() {
     echo "$(date +'[%d/%b/%Y %H:%M:%S %z]') httpd stopped pid=$savedpid" >> $logfile
   fi
 }
+
 reload() {
-  echo -n $"Reloading $prog: "
+  echo -n "Reloading $prog: "
   if ! LANG=C $httpd $OPTIONS -t >&/dev/null; then
     RETVAL=$?
-    echo $"not reloading due to configuration syntax error"
-    failure $"not reloading $httpd due to configuration syntax error"
+    echo "not reloading due to configuration syntax error"
+    failure "not reloading $httpd due to configuration syntax error"
   else
     killproc $httpd -HUP
     RETVAL=$?
@@ -471,6 +515,7 @@ reload() {
   fi
   echo
 }
+
 status() {
   local base=${1##*/}
   local pid
@@ -478,7 +523,7 @@ status() {
   getpidfromexec $1
   pid=$savedpid
   if [ -n "$pid" ]; then
-    echo $"${base} (pid $pid) is running..."
+    echo "${base} (pid $pid) is running..."
     return 0
   fi
 
@@ -486,17 +531,17 @@ status() {
   if [ -f $pidfile ] ; then
     read pid < $pidfile
     if [ -n "$pid" ]; then
-      echo $"${base} dead but pid file exists"
+      echo "${base} dead but pid file exists"
       return 1
     fi
   fi
 
   # See if $lockfile exists
   if [ -f $lockfile ]; then
-    echo $"${base} dead but subsys locked"
+    echo "${base} dead but subsys locked"
     return 2
   fi
-  echo $"${base} is stopped"
+  echo "${base} is stopped"
   return 3
 }
 
@@ -546,7 +591,7 @@ case "$1" in
     ${LYNX-"lynx -dump"} ${STATUSURL-"http://localhost:80/server-status"}
     ;;
   *)
-    echo $"Usage: $prog {start|stop|restart|condrestart|reload|status|fullstatus|graceful|help|configtest}"
+    echo "Usage: $prog {start|stop|restart|condrestart|reload|status|fullstatus|graceful|help|configtest}"
     exit 1
 esac
 
